<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://vo.dadimedia.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="OaTravelService" targetNamespace="http://vo.dadimedia.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://vo.dadimedia.com/" elementFormDefault="unqualified" targetNamespace="http://vo.dadimedia.com/" version="1.0">

  <xs:element name="receiveOaTravel" type="tns:receiveOaTravel"/>

  <xs:element name="receiveOaTravelResponse" type="tns:receiveOaTravelResponse"/>

  <xs:complexType name="receiveOaTravel">
    <xs:sequence>
      <xs:element minOccurs="0" name="travelJson" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="receiveOaTravelResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="receiveOaTravel">
    <wsdl:part element="tns:receiveOaTravel" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="receiveOaTravelResponse">
    <wsdl:part element="tns:receiveOaTravelResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="OaTravelService">
    <wsdl:operation name="receiveOaTravel">
      <wsdl:input message="tns:receiveOaTravel" name="receiveOaTravel">
    </wsdl:input>
      <wsdl:output message="tns:receiveOaTravelResponse" name="receiveOaTravelResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OaTravelServiceSoapBinding" type="tns:OaTravelService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="receiveOaTravel">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="receiveOaTravel">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="receiveOaTravelResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OaTravelService">
    <wsdl:port binding="tns:OaTravelServiceSoapBinding" name="OaTravelServiceImplPort">
      <soap:address location="http://59.110.236.229:8080/oa/travel"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>