<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://vo.dadimedia.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="OaExpendService" targetNamespace="http://vo.dadimedia.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://vo.dadimedia.com/" elementFormDefault="unqualified" targetNamespace="http://vo.dadimedia.com/" version="1.0">

  <xs:element name="receiveOaExpend" type="tns:receiveOaExpend"/>

  <xs:element name="receiveOaExpendResponse" type="tns:receiveOaExpendResponse"/>

  <xs:complexType name="receiveOaExpend">
    <xs:sequence>
      <xs:element minOccurs="0" name="expendJson" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="receiveOaExpendResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="receiveOaExpend">
    <wsdl:part element="tns:receiveOaExpend" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="receiveOaExpendResponse">
    <wsdl:part element="tns:receiveOaExpendResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="OaExpendService">
    <wsdl:operation name="receiveOaExpend">
      <wsdl:input message="tns:receiveOaExpend" name="receiveOaExpend">
    </wsdl:input>
      <wsdl:output message="tns:receiveOaExpendResponse" name="receiveOaExpendResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="OaExpendServiceSoapBinding" type="tns:OaExpendService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="receiveOaExpend">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="receiveOaExpend">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="receiveOaExpendResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="OaExpendService">
    <wsdl:port binding="tns:OaExpendServiceSoapBinding" name="OaExpendServiceImplPort">
      <soap:address location="http://59.110.236.229:8080/oa/expend"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>